### ISSUE TITLE
context menu?

### ISSUE THREAD

**Issue by zinetx** [siddharthkumarjha/custom-vivaldi-css#1]
Hi, do you know the # of the context menu items?
I'm trying to hide elements in context menus in Vivaldi, 
something like
#contentAreaContextMenu menuitem[label*="Copy CSS path to clipboard"] { display: none !important; }

#contentAreaContextMenu menuitem[label*="Google Translate"] { display: none !important; }

Thanks!

**Comment by siddharthkumarjha** [comment]
Please explore on your own using vivaldi's provided dev tools. Go to,

```
vivaldi://inspect/#apps
```

and click on inspect under vivaldi it will allow you to inspect all your browser's elements (eg, address bar, side bar, buttons, etc) like a webpage.

Since this is not an issue related to this repo I am closing it.

Best,
Siddharth
